### ISSUE TITLE
Cursor jumping on HTC One X

### ISSUE THREAD

**Issue by hoverlover** [stripe/jquery.payment#197] opened 2015-12-18 21:07 UTC
I know this has been an issue in the past, but I'm still getting cursor jumping issues for the credit card number field.  [Here's a quick screen recording](https://www.dropbox.com/s/t9pybwj24cfyb6r/HTC%20One%20X%20cursor%20jumping.mov?dl=0) that shows it.

I found out because a customer of mine using an HTC One reported the issue, and I verified it using the HTC One X emulator in BrowserStack.

I'm not sure I know what to do to fix this.  I'll give it a shot, but in the meantime it would be great if someone who knew what they were doing could take a look and see if they could fix it.

Thanks!

**Comment by hoverlover** [comment] 2015-12-18 22:19
I think I've narrowed it down to these [two](https://github.com/stripe/jquery.payment/blob/master/lib/jquery.payment.js#L211) [lines](https://github.com/stripe/jquery.payment/blob/master/lib/jquery.payment.js#L253).

Seems the delays of the two `setTimeout` calls are colliding somehow, causing the cursor to be positioned before the formatting takes place.  If I remove those timeouts everything seems to work fine no matter how fast I type.

Can someone tell me why those `setTimeout` calls are even needed?  It's not obvious to me.

**Comment by hoverlover** [comment] 2015-12-18 22:50
Spoke too soon :disappointed: It did seem to help it not happen as often, but I'm still getting the cursor ending up in the wrong place, even after commenting those lines.

**Comment by jamesreggio** [comment] 2015-12-19 20:29
Yep, this is a persistent problem in mobile Firefox (which I assume you are
using). The setTimeout calls were actually designed to 'fix' the cursor
positioning by re-writing the value of the field after a fixed delay.
(Certain browsers reposition the cursor to the end of the value when it is
programmatically changed.)

The problem is endemic to this library, and I don't think it can be
definitively resolved without a total rewrite. I can suggest two
workarounds for you, though:

- increase the delay in the setTimeout calls until the problem resolves
(something in the range of 100-300ms should suit, but will regress the
experience of your other users)
- disable jQuery.payment on the troublesome browsers (this is not something
we were comfortable baking into the library since it requires user-agent
matching)

Hope this helps.

**Comment by hoverlover** [comment] 2015-12-19 22:53
Thanks, James.  I opted to take the latter approach and disable it based on Android version.  Wish I could support formatting on all mobile browsers, but I was just having too much trouble.  It's not just this library, btw. I tried several other formatting libraries out there, and none of them worked properly.  Thanks for your reply!

**Comment by jamesreggio** [comment] 2015-12-20 00:27
No worries.

I'm working on a (long-awaited, fabled) replacement, so I'll ping this
issue again when it's ready.

**Comment by jenanwise** [comment] 2016-01-17 06:14
@hoverlover To follow up -- thanks for the report! Going to close as "can't fix without breaking everything else" :cry: And I'll let James ping this thread when his magic new library is available :grin:

**Closed by jenanwise** 2016-01-17 06:14 UTC
Labels: bug
