### ISSUE TITLE
formatCardExpiry fails on certain browsers

### ISSUE THREAD

**Issue by sidwyn** [stripe/jquery.payment#226] opened 2016-05-13 23:25 UTC
## Expected behavior

On Android 5.0.1 on Samsung Galaxy S4, using Chrome 50.0.2661.89, card expiry should be able to take 10/18 as a valid month/year expiry on http://gofundme.com/parsen9/donate. We're calling the formatCardExpiry on any input into the MM/YY input field. However, the function formats it differently on the Chrome browser with respect to that specific device (S4)

## Actual behavior

When trying to type 10/18 in the MM/YY field, we get 1/018 instead. There seems to be some problem with the formatting specifically with respect to the formatCardExpiry method.

## Steps to reproduce

On a similar mobile device, go to http://gofundme.com/parsen9/donate, and then fill out the first form. On the second page, try to enter 10/18 as the MM/YY expiry, and notice it failing.

**Comment by jenanwise** [comment] 2016-05-18 01:03
@sidwyn Unfortunately, I don't have that particular device/browser combination available for testing. Can you (1) create a minimal jsfiddle reproducing the problem and (2) help identify exactly what is failing? I'm not sure why that particular combination would have trouble. Thanks!

**Comment by jenanwise** [comment] 2016-07-07 03:00
Closing due to lack of info. Please reopen with more details if the problem persists!

**Closed by jenanwise** 2016-07-07 03:00 UTC
Labels: needs-more-info
