### ISSUE TITLE
Bug in card number formatting

### ISSUE THREAD

**Issue by tipsy** [stripe/jquery.payment#199] opened 2016-01-15 15:52 UTC
In the card number field, enter
`4444`, then `left`, then `1234`. 
Expected: `44441234`
Actual:  `44442341`

I haven't looked at your implementation, so I'm not sure if this is useful information, but when I was emulating the behavior of your plugin I fixed this bug by increasing the caret position by 1 if it was currently at an index which should be a whitespace.

**Comment by jenanwise** [comment] 2016-01-15 19:02
Thanks for reporting. Confirmed that this is an issue.

**Comment by optimizamx** [comment] 2016-02-12 19:22
Apparently this bug was fixed, but the jquery.payment version didn't changed?

**Comment by jenanwise** [comment] 2016-02-18 01:08
@optimizamx Still looks like an issue to me.

**Comment by optimizamx** [comment] 2016-02-18 01:55
@jenanwise you are correct!

We were using the jquery.payment version that comes with the latest Woocommerce version (2.5.2) and it had the exact same problem, and then we replaced it with this version and now what it does is:

`4444`, then `left `, then `1234 `
Expected: `44441234`
Actual: `44413424`

**Comment by lfarmer** [comment] 2016-04-04 14:22
Hi,

We are experiencing similar issues...  during testing of card payments we have encountered the following:

1. Enter card number: 5569 5100 0000 3698, with other card details
2. Submit, expecting LUHN check failure
3. Edit card number to valid number 5569 5112 3456 3698

Issue arises when editing the card number and deleting the invalid digits 000000.  Whilst typing 123456, formatter seems to shift the cursor back after entering no. 3 in the above combination.

This results in having the following credit card number

5569 5112 4563 3698, which fails LUHN check

**Comment by awendt** [comment] 2016-04-08 09:31
Any idea when/if this is going to be fixed?

**Comment by jenanwise** [comment] 2016-04-18 17:19
Should be fixed in master. I'll try and cut a release later this week.

**Closed** 2016-04-18 17:19 UTC
Labels: bug
